// Fallback estático alinhado com seeds do Excel (usado quando a API está offline).
// Valores TEXT (descricao) — PT_EFLUENTE armazena texto, não FK int.
// FONTE DA VERDADE: 20260306_MODELAGEM_APP_EFLUENTE.xlsx aba Domínios.

export const PROFILE_OPTIONS = [
  { value: 'ADMINISTRADOR', label: 'ADMINISTRADOR' },
  { value: 'USUARIO_CAMPO', label: 'USUARIO_CAMPO' },
]

export const DEPTO_OPTIONS = [
  { value: 'GEA', label: 'GEA' },
  { value: 'GEA.DEAE', label: 'GEA.DEAE' },
  { value: 'GEA.DEAO', label: 'GEA.DEAO' },
  { value: 'Não se aplica(m)', label: 'Não se aplica(m)' },
  { value: 'Inexistente(s)', label: 'Inexistente(s)' },
  { value: 'Indefinido(a)(s)', label: 'Indefinido(a)(s)' },
  { value: 'Não avaliado(a)(s)', label: 'Não avaliado(a)(s)' },
]

export const STATUS_DESVIO_OPTIONS = [
  { value: 'Não Regularizado', label: 'Não Regularizado' },
  { value: 'Regularizado', label: 'Regularizado' },
  { value: 'Não se aplica(m)', label: 'Não se aplica(m)' },
  { value: 'Inexistente(s)', label: 'Inexistente(s)' },
  { value: 'Indefinido(a)(s)', label: 'Indefinido(a)(s)' },
  { value: 'Não avaliado(a)(s)', label: 'Não avaliado(a)(s)' },
]

export const STATUS_REGISTRO_OPTIONS = [
  { value: 'Ativo', label: 'Ativo' },
  { value: 'Inativo', label: 'Inativo' },
  { value: 'Não se aplica(m)', label: 'Não se aplica(m)' },
  { value: 'Inexistente(s)', label: 'Inexistente(s)' },
  { value: 'Indefinido(a)(s)', label: 'Indefinido(a)(s)' },
  { value: 'Não avaliado(a)(s)', label: 'Não avaliado(a)(s)' },
]

export const MUNICIPIO_OPTIONS = [
  { value: 'Arujá', label: 'Arujá' },
  { value: 'Barueri', label: 'Barueri' },
  { value: 'Biritiba-Mirim', label: 'Biritiba-Mirim' },
  { value: 'Caieiras', label: 'Caieiras' },
  { value: 'Cajamar', label: 'Cajamar' },
  { value: 'Campo Limpo Paulista', label: 'Campo Limpo Paulista' },
  { value: 'Carapicuíba', label: 'Carapicuíba' },
  { value: 'Cotia', label: 'Cotia' },
  { value: 'Diadema', label: 'Diadema' },
  { value: 'Embu', label: 'Embu' },
  { value: 'Embu-Guaçu', label: 'Embu-Guaçu' },
  { value: 'Ferraz de Vasconcelos', label: 'Ferraz de Vasconcelos' },
  { value: 'Francisco Morato', label: 'Francisco Morato' },
  { value: 'Franco da Rocha', label: 'Franco da Rocha' },
  { value: 'Guararema', label: 'Guararema' },
  { value: 'Guarulhos', label: 'Guarulhos' },
  { value: 'Itapecerica da Serra', label: 'Itapecerica da Serra' },
  { value: 'Itapevi', label: 'Itapevi' },
  { value: 'Itaquaquecetuba', label: 'Itaquaquecetuba' },
  { value: 'Jandira', label: 'Jandira' },
  { value: 'Jundiaí', label: 'Jundiaí' },
  { value: 'Juqutiba', label: 'Juqutiba' },
  { value: 'Mairinque', label: 'Mairinque' },
  { value: 'Mairiporã', label: 'Mairiporã' },
  { value: 'Mauá', label: 'Mauá' },
  { value: 'Mogi das Cruzes', label: 'Mogi das Cruzes' },
  { value: 'Osasco', label: 'Osasco' },
  { value: 'Pirapora do Bom Jesus', label: 'Pirapora do Bom Jesus' },
  { value: 'Poá', label: 'Poá' },
  { value: 'Ribeirão Pires', label: 'Ribeirão Pires' },
  { value: 'Rio Grande da Serra', label: 'Rio Grande da Serra' },
  { value: 'Salesópolis', label: 'Salesópolis' },
  { value: 'Santa Isabel', label: 'Santa Isabel' },
  { value: 'Santana de Parnaíba', label: 'Santana de Parnaíba' },
  { value: 'Santo André', label: 'Santo André' },
  { value: 'Santos', label: 'Santos' },
  { value: 'São Bernardo do Campo', label: 'São Bernardo do Campo' },
  { value: 'São Caetano do Sul', label: 'São Caetano do Sul' },
  { value: 'São Lourenço da Serra', label: 'São Lourenço da Serra' },
  { value: 'São Paulo', label: 'São Paulo' },
  { value: 'São Roque', label: 'São Roque' },
  { value: 'São Vicente', label: 'São Vicente' },
  { value: 'Suzano', label: 'Suzano' },
  { value: 'Taboão da Serra', label: 'Taboão da Serra' },
  { value: 'Vargem Grande Paulista', label: 'Vargem Grande Paulista' },
  { value: 'Várzea Paulista', label: 'Várzea Paulista' },
  { value: 'Diversos (Ver Observação)', label: 'Diversos (Ver Observação)' },
  { value: 'Não se aplica(m)', label: 'Não se aplica(m)' },
  { value: 'Inexistente(s)', label: 'Inexistente(s)' },
  { value: 'Indefinido(a)(s)', label: 'Indefinido(a)(s)' },
  { value: 'Não avaliado(a)(s)', label: 'Não avaliado(a)(s)' },
]

export const LINHA_OPTIONS = [
  { value: 'Linha 07 - Rubi', label: 'Linha 07 - Rubi' },
  { value: 'Linha 08 - Diamante', label: 'Linha 08 - Diamante' },
  { value: 'Linha 09 - Esmeralda', label: 'Linha 09 - Esmeralda' },
  { value: 'Linha 10 - Turquesa', label: 'Linha 10 - Turquesa' },
  { value: 'Linha 11 - Coral', label: 'Linha 11 - Coral' },
  { value: 'Linha 12 - Safira', label: 'Linha 12 - Safira' },
  { value: 'Linha 13 - Jade', label: 'Linha 13 - Jade' },
  { value: 'Linha 05 - Lilás', label: 'Linha 05 - Lilás' },
  { value: 'Linha JJ - Baixada Santista', label: 'Linha JJ - Baixada Santista' },
  { value: 'Sem linha associada', label: 'Sem linha associada' },
  { value: 'Linha não informada', label: 'Linha não informada' },
  { value: 'Não se aplica(m)', label: 'Não se aplica(m)' },
  { value: 'Inexistente(s)', label: 'Inexistente(s)' },
  { value: 'Indefinido(a)(s)', label: 'Indefinido(a)(s)' },
  { value: 'Não avaliado(a)(s)', label: 'Não avaliado(a)(s)' },
]

export const VIA_OPTIONS = [
  { value: 'Via 01', label: 'Via 01' },
  { value: 'Via 02', label: 'Via 02' },
  { value: 'Via 03', label: 'Via 03' },
  { value: 'Via 04', label: 'Via 04' },
  { value: 'Via 05', label: 'Via 05' },
  { value: 'Via 06', label: 'Via 06' },
  { value: 'Via 08', label: 'Via 08' },
  { value: 'Via 09', label: 'Via 09' },
  { value: 'Via 10', label: 'Via 10' },
  { value: 'Via 01S - Trecho 1', label: 'Via 01S - Trecho 1' },
  { value: 'Via 01S - Trecho 2', label: 'Via 01S - Trecho 2' },
  { value: 'Via 02S - Trecho 1', label: 'Via 02S - Trecho 1' },
  { value: 'Via 02S - Trecho 2', label: 'Via 02S - Trecho 2' },
  { value: 'Via 03S - Trecho 2', label: 'Via 03S - Trecho 2' },
  { value: 'Via 03E - Trecho 2', label: 'Via 03E - Trecho 2' },
  { value: 'Via 04E - Trecho 2', label: 'Via 04E - Trecho 2' },
  { value: 'Via Auxiliar', label: 'Via Auxiliar' },
  { value: 'Via Variante', label: 'Via Variante' },
  { value: 'Travessão - AMV', label: 'Travessão - AMV' },
  { value: 'Não se aplica(m)', label: 'Não se aplica(m)' },
  { value: 'Inexistente(s)', label: 'Inexistente(s)' },
  { value: 'Indefinido(a)(s)', label: 'Indefinido(a)(s)' },
  { value: 'Não avaliado(a)(s)', label: 'Não avaliado(a)(s)' },
]

export const TRECHO_OPTIONS = [
  { value: 'Estação Aeroporto Guarulhos - Estação Guarulhos - Cecap', label: 'Estação Aeroporto Guarulhos - Estação Guarulhos - Cecap' },
  { value: 'Estação Água Branca - Estação Lapa', label: 'Estação Água Branca - Estação Lapa' },
  { value: 'Estação Barra Funda - Estação Luz', label: 'Estação Barra Funda - Estação Luz' },
  { value: 'Estação Caieiras - Estação Franco da Rocha', label: 'Estação Caieiras - Estação Franco da Rocha' },
  { value: 'Estação Campo Limpo Paulista - Estação Botujuru', label: 'Estação Campo Limpo Paulista - Estação Botujuru' },
  { value: 'Estação Corinthians - Itaquera - Estação Tatuapé', label: 'Estação Corinthians - Itaquera - Estação Tatuapé' },
  { value: 'Estação Francisco Morato - Estação Baltazar Fidelis', label: 'Estação Francisco Morato - Estação Baltazar Fidelis' },
  { value: 'Estação Guarulhos - Cecap - Estação Engenheiro Goulart', label: 'Estação Guarulhos - Cecap - Estação Engenheiro Goulart' },
  { value: 'Estação Ipiranga - Estação Tamanduateí', label: 'Estação Ipiranga - Estação Tamanduateí' },
  { value: 'Estação Jundiapeba - Estação Suzano', label: 'Estação Jundiapeba - Estação Suzano' },
  { value: 'Estação Lapa (Linha 07) - Estação Água Branca', label: 'Estação Lapa (Linha 07) - Estação Água Branca' },
  { value: 'Estação Luz - Estação Barra Funda', label: 'Estação Luz - Estação Barra Funda' },
  { value: 'Estação Mogi das Cruzes - Estação Estudantes', label: 'Estação Mogi das Cruzes - Estação Estudantes' },
  { value: 'Estação Palmeiras - Barra Funda - Estação Água Branca', label: 'Estação Palmeiras - Barra Funda - Estação Água Branca' },
  { value: 'Estação Perus - Estação Caieiras', label: 'Estação Perus - Estação Caieiras' },
  { value: 'Estação Pirituba - Estação Vila Clarisse', label: 'Estação Pirituba - Estação Vila Clarisse' },
  { value: 'Estação Ribeirão Pires - Estação Rio Grande da Serra', label: 'Estação Ribeirão Pires - Estação Rio Grande da Serra' },
  { value: 'Estação Roosevelt/Brás - Estação Luz', label: 'Estação Roosevelt/Brás - Estação Luz' },
  { value: 'Estação Santo André - Estação Capuava', label: 'Estação Santo André - Estação Capuava' },
  { value: 'Estação Suzano - Estação Calmon Viana', label: 'Estação Suzano - Estação Calmon Viana' },
  { value: 'Estação Tatuapé - Estação Engenheiro Goulart', label: 'Estação Tatuapé - Estação Engenheiro Goulart' },
  { value: 'Estação Várzea Paulista - Estação Jundiaí', label: 'Estação Várzea Paulista - Estação Jundiaí' },
  { value: 'Final dos Trilhos - Estação Estudantes', label: 'Final dos Trilhos - Estação Estudantes' },
  { value: 'Não se aplica(m)', label: 'Não se aplica(m)' },
  { value: 'Inexistente(s)', label: 'Inexistente(s)' },
  { value: 'Indefinido(a)(s)', label: 'Indefinido(a)(s)' },
  { value: 'Não avaliado(a)(s)', label: 'Não avaliado(a)(s)' },
]

export const ESTACAO_OPTIONS = [
  { value: 'Estação Aeroporto Guarulhos', label: 'Estação Aeroporto Guarulhos' },
  { value: 'Estação Água Branca', label: 'Estação Água Branca' },
  { value: 'Estação Aracaré', label: 'Estação Aracaré' },
  { value: 'Estação Baltazar Fidelis', label: 'Estação Baltazar Fidelis' },
  { value: 'Estação Barueri', label: 'Estação Barueri' },
  { value: 'Estação Botujuru', label: 'Estação Botujuru' },
  { value: 'Estação Brás', label: 'Estação Brás' },
  { value: 'Estação Brás Cubas', label: 'Estação Brás Cubas' },
  { value: 'Estação Caieiras', label: 'Estação Caieiras' },
  { value: 'Estação Calmon Viana', label: 'Estação Calmon Viana' },
  { value: 'Estação Campo Limpo Paulista', label: 'Estação Campo Limpo Paulista' },
  { value: 'Estação Capuava', label: 'Estação Capuava' },
  { value: 'Estação Carapicuíba', label: 'Estação Carapicuíba' },
  { value: 'Estação Corinthians - Itaquera', label: 'Estação Corinthians - Itaquera' },
  { value: 'Estação Dom Bosco', label: 'Estação Dom Bosco' },
  { value: 'Estação Engenheiro Goulart', label: 'Estação Engenheiro Goulart' },
  { value: 'Estação Engenheiro Manoel Feio', label: 'Estação Engenheiro Manoel Feio' },
  { value: 'Estação Estudantes', label: 'Estação Estudantes' },
  { value: 'Estação Ferraz de Vasconcelos', label: 'Estação Ferraz de Vasconcelos' },
  { value: 'Estação Francisco Morato', label: 'Estação Francisco Morato' },
  { value: 'Estação Franco da Rocha', label: 'Estação Franco da Rocha' },
  { value: 'Estação Guaianazes', label: 'Estação Guaianazes' },
  { value: 'Estação Guarulhos Cecap', label: 'Estação Guarulhos Cecap' },
  { value: 'Estação Ipiranga', label: 'Estação Ipiranga' },
  { value: 'Estação Itapevi', label: 'Estação Itapevi' },
  { value: 'Estação Itaquaquecetuba', label: 'Estação Itaquaquecetuba' },
  { value: 'Estação Jandira', label: 'Estação Jandira' },
  { value: 'Estação Jardim Romano', label: 'Estação Jardim Romano' },
  { value: 'Estação José Bonifácio', label: 'Estação José Bonifácio' },
  { value: 'Estação Jundiaí', label: 'Estação Jundiaí' },
  { value: 'Estação Jundiapeba', label: 'Estação Jundiapeba' },
  { value: 'Estação Lapa (Linha 7)', label: 'Estação Lapa (Linha 7)' },
  { value: 'Estação Lapa (Linha 8)', label: 'Estação Lapa (Linha 8)' },
  { value: 'Estação Luz', label: 'Estação Luz' },
  { value: 'Estação Mauá', label: 'Estação Mauá' },
  { value: 'Estação Mogi das Cruzes', label: 'Estação Mogi das Cruzes' },
  { value: 'Estação Osasco', label: 'Estação Osasco' },
  { value: 'Estação Palmeiras - Barra Funda', label: 'Estação Palmeiras - Barra Funda' },
  { value: 'Estação Perus', label: 'Estação Perus' },
  { value: 'Estação Piqueri', label: 'Estação Piqueri' },
  { value: 'Estação Pirituba', label: 'Estação Pirituba' },
  { value: 'Estação Poá', label: 'Estação Poá' },
  { value: 'Estação Prefeito Celso Daniel - Santo André', label: 'Estação Prefeito Celso Daniel - Santo André' },
  { value: 'Estação Ribeirão Pires', label: 'Estação Ribeirão Pires' },
  { value: 'Estação Rio Grande da Serra', label: 'Estação Rio Grande da Serra' },
  { value: 'Estação Roosevelt/Brás', label: 'Estação Roosevelt/Brás' },
  { value: 'Estação Santo André', label: 'Estação Santo André' },
  { value: 'Estação São Caetano', label: 'Estação São Caetano' },
  { value: 'Estação São Miguel Paulista', label: 'Estação São Miguel Paulista' },
  { value: 'Estação Suzano', label: 'Estação Suzano' },
  { value: 'Estação Tamanduateí', label: 'Estação Tamanduateí' },
  { value: 'Estação Tatuapé', label: 'Estação Tatuapé' },
  { value: 'Estação USP Leste', label: 'Estação USP Leste' },
  { value: 'Estação Utinga', label: 'Estação Utinga' },
  { value: 'Estação Várzea Paulista', label: 'Estação Várzea Paulista' },
  { value: 'Estação Vila Aurora', label: 'Estação Vila Aurora' },
  { value: 'Estação Vila Clarisse', label: 'Estação Vila Clarisse' },
  { value: 'Não se aplica(m)', label: 'Não se aplica(m)' },
  { value: 'Inexistente(s)', label: 'Inexistente(s)' },
  { value: 'Indefinido(a)(s)', label: 'Indefinido(a)(s)' },
  { value: 'Não avaliado(a)(s)', label: 'Não avaliado(a)(s)' },
]

export const NATUREZA_PGA_OPTIONS = [
  { value: 'Áreas Ambientalmente Protegidas', label: 'Áreas Ambientalmente Protegidas' },
  { value: 'Áreas Contaminadas', label: 'Áreas Contaminadas' },
  { value: 'Arqueologia', label: 'Arqueologia' },
  { value: 'Comunicação Social', label: 'Comunicação Social' },
  { value: 'Documentação', label: 'Documentação' },
  { value: 'Efluente', label: 'Efluente' },
  { value: 'Emissões Atmosféricas', label: 'Emissões Atmosféricas' },
  { value: 'Erosões e Movimentos de Massa', label: 'Erosões e Movimentos de Massa' },
  { value: 'Fauna', label: 'Fauna' },
  { value: 'Gerenciamento de Solo', label: 'Gerenciamento de Solo' },
  { value: 'Lançamentos Irregulares', label: 'Lançamentos Irregulares' },
  { value: 'Patrimônio Histórico', label: 'Patrimônio Histórico' },
  { value: 'Produtos Perigosos', label: 'Produtos Perigosos' },
  { value: 'Recursos Hídricos', label: 'Recursos Hídricos' },
  { value: 'Resíduos Sólidos', label: 'Resíduos Sólidos' },
  { value: 'Ruído e Vibração', label: 'Ruído e Vibração' },
  { value: 'Segmentação Urbana', label: 'Segmentação Urbana' },
  { value: 'Sinalização e Isolamento', label: 'Sinalização e Isolamento' },
  { value: 'Sistema de Drenagem, Inundações e Alagamentos', label: 'Sistema de Drenagem, Inundações e Alagamentos' },
  { value: 'Vegetação', label: 'Vegetação' },
  { value: 'Não se aplica(m)', label: 'Não se aplica(m)' },
  { value: 'Inexistente(s)', label: 'Inexistente(s)' },
  { value: 'Indefinido(a)(s)', label: 'Indefinido(a)(s)' },
  { value: 'Não avaliado(a)(s)', label: 'Não avaliado(a)(s)' },
]

export const AREA_GESTORA_OPTIONS = [
  { value: '(DE.GEA.0000) GERENCIA DE MEIO AMBIENTE [ID.10-14-4-0-0000]', label: '(DE.GEA.0000) GERENCIA DE MEIO AMBIENTE [ID.10-14-4-0-0000]' },
  { value: '(DE.GEA.DEAE.0000) DEPTO. DE MEIO AMBIENTE - EMPREENDIMENTOS [ID.10-14-4-1-0000]', label: '(DE.GEA.DEAE.0000) DEPTO. DE MEIO AMBIENTE - EMPREENDIMENTOS [ID.10-14-4-1-0000]' },
  { value: '(DE.GEA.DEAO.0000) DEPTO. DE MEIO AMBIENTE - OPERACAO [ID.10-14-4-2-0000]', label: '(DE.GEA.DEAO.0000) DEPTO. DE MEIO AMBIENTE - OPERACAO [ID.10-14-4-2-0000]' },
  { value: '(DE.GEF.0000) GERENCIA DE EMPREENDIMENTOS [ID.10-14-6-0-0000]', label: '(DE.GEF.0000) GERENCIA DE EMPREENDIMENTOS [ID.10-14-6-0-0000]' },
  { value: '(DE.GEP.0000) GERENCIA DE PROJETOS [ID.10-14-1-0-0000]', label: '(DE.GEP.0000) GERENCIA DE PROJETOS [ID.10-14-1-0-0000]' },
  { value: '(DO.GOF.0000) GERENCIA DE MANUT. DE EQUIPAMENTOS FIXOS [ID.10-15-5-0-0000]', label: '(DO.GOF.0000) GERENCIA DE MANUT. DE EQUIPAMENTOS FIXOS [ID.10-15-5-0-0000]' },
  { value: '(DO.GOV.0000) GERENCIA DE MANUT. DE VIA PERMANENTE E ESTRUTURA CIVIL [ID.10-15-6-0-0000]', label: '(DO.GOV.0000) GERENCIA DE MANUT. DE VIA PERMANENTE E ESTRUTURA CIVIL [ID.10-15-6-0-0000]' },
  { value: '(DO.GOR.0000) GERENCIA MANUT. MAT RODANTE E OFICINAS [ID.10-15-3-0-0000]', label: '(DO.GOR.0000) GERENCIA MANUT. MAT RODANTE E OFICINAS [ID.10-15-3-0-0000]' },
  { value: '(DO.GOO.0000) GERENCIA GERAL DE OPERACAO [ID.10-16-1-0-0000]', label: '(DO.GOO.0000) GERENCIA GERAL DE OPERACAO [ID.10-16-1-0-0000]' },
  { value: '(DP.GPN.0000) GERENCIA DE NOVOS NEGOCIOS [ID.10-13-4-0-0000]', label: '(DP.GPN.0000) GERENCIA DE NOVOS NEGOCIOS [ID.10-13-4-0-0000]' },
  { value: 'Não se aplica(m)', label: 'Não se aplica(m)' },
  { value: 'Inexistente(s)', label: 'Inexistente(s)' },
  { value: 'Indefinido(a)(s)', label: 'Indefinido(a)(s)' },
  { value: 'Não avaliado(a)(s)', label: 'Não avaliado(a)(s)' },
]

export const PROPRIETARIO_OPTIONS = [
  { value: 'CPTM - Titularidade', label: 'CPTM - Titularidade' },
  { value: 'CPTM - Posse', label: 'CPTM - Posse' },
  { value: 'Metrô', label: 'Metrô' },
  { value: 'Alienado', label: 'Alienado' },
  { value: 'MRS', label: 'MRS' },
  { value: 'RFSA', label: 'RFSA' },
  { value: 'RFSA/SPU', label: 'RFSA/SPU' },
  { value: 'CBTU', label: 'CBTU' },
  { value: 'Pessoa Jurídica', label: 'Pessoa Jurídica' },
  { value: 'Pessoa Física', label: 'Pessoa Física' },
  { value: 'Indefinido', label: 'Indefinido' },
  { value: 'FEPASA', label: 'FEPASA' },
  { value: 'Permuta', label: 'Permuta' },
  { value: 'Prefeitura de Guarulhos', label: 'Prefeitura de Guarulhos' },
  { value: 'DAEE', label: 'DAEE' },
  { value: 'USP Leste', label: 'USP Leste' },
  { value: 'GRU - Aeroporto', label: 'GRU - Aeroporto' },
  { value: 'CCR - Rodovia Dutra', label: 'CCR - Rodovia Dutra' },
  { value: 'Ecopistas', label: 'Ecopistas' },
  { value: 'CDHU', label: 'CDHU' },
  { value: 'Não se aplica(m)', label: 'Não se aplica(m)' },
  { value: 'Inexistente(s)', label: 'Inexistente(s)' },
  { value: 'Não avaliado(a)(s)', label: 'Não avaliado(a)(s)' },
]

export const SIM_NAO_OPTIONS = [
  { value: 'Sim', label: 'Sim' },
  { value: 'Não', label: 'Não' },
  { value: 'Não Informado', label: 'Não Informado' },
  { value: 'Não se aplica(m)', label: 'Não se aplica(m)' },
  { value: 'Inexistente(s)', label: 'Inexistente(s)' },
  { value: 'Indefinido(a)(s)', label: 'Indefinido(a)(s)' },
  { value: 'Não avaliado(a)(s)', label: 'Não avaliado(a)(s)' },
]

export const TIPO_ATIVIDADE_OPTIONS = [
  { value: 'Estação de Tratamento de Efluente', label: 'Estação de Tratamento de Efluente' },
  { value: 'Transporte', label: 'Transporte' },
  { value: 'Outro(a)(s)', label: 'Outro(a)(s)' },
  { value: 'Indefinido(a)(s)', label: 'Indefinido(a)(s)' },
  { value: 'Não se aplica(m)', label: 'Não se aplica(m)' },
  { value: 'Inexistente(s)', label: 'Inexistente(s)' },
  { value: 'Não avaliado(a)(s)', label: 'Não avaliado(a)(s)' },
]

export const TIPO_DRA_OPTIONS = [
  { value: 'Cadastro Técnico Federal (IBAMA) - CTF/IBAMA', label: 'Cadastro Técnico Federal (IBAMA) - CTF/IBAMA' },
  { value: 'Certificado de Dispensa de Licença - CDL', label: 'Certificado de Dispensa de Licença - CDL' },
  { value: 'Certificado de Movimentação de Resíduos de Interesse Ambiental - CADRI', label: 'Certificado de Movimentação de Resíduos de Interesse Ambiental - CADRI' },
  { value: 'Declaração de Movimentação de Resíduos - DMR', label: 'Declaração de Movimentação de Resíduos - DMR' },
  { value: 'Ficha de Informações de Segurança de Produtos Químicos - FISPQ', label: 'Ficha de Informações de Segurança de Produtos Químicos - FISPQ' },
  { value: 'Licença de Operação - LO', label: 'Licença de Operação - LO' },
  { value: 'Manifesto de Transporte de Resíduos - MTR', label: 'Manifesto de Transporte de Resíduos - MTR' },
  { value: 'Outro(a)(s)', label: 'Outro(a)(s)' },
  { value: 'Indefinido(a)(s)', label: 'Indefinido(a)(s)' },
  { value: 'Não se aplica(m)', label: 'Não se aplica(m)' },
  { value: 'Inexistente(s)', label: 'Inexistente(s)' },
  { value: 'Não avaliado(a)(s)', label: 'Não avaliado(a)(s)' },
]

export const TIPO_ATIV_CPTM_OPTIONS = [
  { value: 'Empreendimento/Obra', label: 'Empreendimento/Obra' },
  { value: 'Manutenção', label: 'Manutenção' },
  { value: 'Operação', label: 'Operação' },
  { value: 'Outro(a)(s)', label: 'Outro(a)(s)' },
  { value: 'Indefinido(a)(s)', label: 'Indefinido(a)(s)' },
  { value: 'Não se aplica(m)', label: 'Não se aplica(m)' },
  { value: 'Inexistente(s)', label: 'Inexistente(s)' },
  { value: 'Não avaliado(a)(s)', label: 'Não avaliado(a)(s)' },
]

export const LOCAL_ATIVIDADE_OPTIONS = [
  { value: 'Abrigo', label: 'Abrigo' },
  { value: 'Base de manutenção', label: 'Base de manutenção' },
  { value: 'Cabine Primária', label: 'Cabine Primária' },
  { value: 'Cabine Seccionadora', label: 'Cabine Seccionadora' },
  { value: 'Estação', label: 'Estação' },
  { value: 'Lavador de TUE', label: 'Lavador de TUE' },
  { value: 'Oficina', label: 'Oficina' },
  { value: 'Pátio', label: 'Pátio' },
  { value: 'Prédio administrativo', label: 'Prédio administrativo' },
  { value: 'Prédio de apoio', label: 'Prédio de apoio' },
  { value: 'Sala técnica', label: 'Sala técnica' },
  { value: 'Subestação', label: 'Subestação' },
  { value: 'Trecho - Km/poste', label: 'Trecho - Km/poste' },
  { value: 'Vários', label: 'Vários' },
  { value: 'Outro(a)(s)', label: 'Outro(a)(s)' },
  { value: 'Indefinido(a)(s)', label: 'Indefinido(a)(s)' },
  { value: 'Não se aplica(m)', label: 'Não se aplica(m)' },
  { value: 'Inexistente(s)', label: 'Inexistente(s)' },
  { value: 'Não avaliado(a)(s)', label: 'Não avaliado(a)(s)' },
]

export const ORIGEM_EFLUENTE_OPTIONS = [
  { value: 'Doméstico/Sanitário', label: 'Doméstico/Sanitário' },
  { value: 'Fundação', label: 'Fundação' },
  { value: 'Industrial', label: 'Industrial' },
  { value: 'Outro(a)(s)', label: 'Outro(a)(s)' },
  { value: 'Indefinido(a)(s)', label: 'Indefinido(a)(s)' },
  { value: 'Não se aplica(m)', label: 'Não se aplica(m)' },
  { value: 'Inexistente(s)', label: 'Inexistente(s)' },
  { value: 'Não avaliado(a)(s)', label: 'Não avaliado(a)(s)' },
]

export const FONTE_GERADORA_OPTIONS = [
  { value: 'Atividade de obra', label: 'Atividade de obra' },
  { value: 'Banheiro químico', label: 'Banheiro químico' },
  { value: 'Banheiros/vestiários/refeitórios', label: 'Banheiros/vestiários/refeitórios' },
  { value: 'Fossa séptica', label: 'Fossa séptica' },
  { value: 'Lavagem de trens/peças', label: 'Lavagem de trens/peças' },
  { value: 'Manutenção ETE', label: 'Manutenção ETE' },
  { value: 'Valas de manutenção', label: 'Valas de manutenção' },
  { value: 'Outro(a)(s)', label: 'Outro(a)(s)' },
  { value: 'Indefinido(a)(s)', label: 'Indefinido(a)(s)' },
  { value: 'Não se aplica(m)', label: 'Não se aplica(m)' },
  { value: 'Inexistente(s)', label: 'Inexistente(s)' },
  { value: 'Não avaliado(a)(s)', label: 'Não avaliado(a)(s)' },
]

export const TIPO_DESTINACAO_OPTIONS = [
  { value: 'Esgotamento e transporte', label: 'Esgotamento e transporte' },
  { value: 'Interligação em rede coletora', label: 'Interligação em rede coletora' },
  { value: 'Lançamento em galeria de águas pluviais', label: 'Lançamento em galeria de águas pluviais' },
  { value: 'Reinfiltração', label: 'Reinfiltração' },
  { value: 'Tratamento em ETE', label: 'Tratamento em ETE' },
  { value: 'Outro(a)(s)', label: 'Outro(a)(s)' },
  { value: 'Indefinido(a)(s)', label: 'Indefinido(a)(s)' },
  { value: 'Não se aplica(m)', label: 'Não se aplica(m)' },
  { value: 'Inexistente(s)', label: 'Inexistente(s)' },
  { value: 'Não avaliado(a)(s)', label: 'Não avaliado(a)(s)' },
]

export const TIPO_VEICULO_OPTIONS = [
  { value: 'Caminhão', label: 'Caminhão' },
  { value: 'Outro(a)(s)', label: 'Outro(a)(s)' },
  { value: 'Indefinido(a)(s)', label: 'Indefinido(a)(s)' },
  { value: 'Não se aplica(m)', label: 'Não se aplica(m)' },
  { value: 'Inexistente(s)', label: 'Inexistente(s)' },
  { value: 'Não avaliado(a)(s)', label: 'Não avaliado(a)(s)' },
]
